name: Update README ⭐
on:
  schedule:
    - cron: "51 */4 1-25 12 *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2455716
          leaderboardId: 2455716
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2023
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
